version: "3.6"

services:
  worker:
    image: ghcr.io/kpott/homemonitor/worker:main
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RabbitMq__Uri=rabbitmq://rabbitmq:5672
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
      - Monitor__Location=Master Bedroom
      - Monitor__DelayBetweenMeasurementsMs=300000
      - Monitor__SensorType=bme280
      - I2C__BusId=1
      - I2C__DeviceAddress=40
    devices:
      - /dev/i2c-1:/dev/i2c-1
    networks:
      - homemonitor
