version: "3.6"

services:
  worker:
    image: ghcr.io/kpott/homemonitor/worker:main
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RabbitMq__Uri=rabbitmq://rabbitmq:5672
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
      - Sensor__Location=Master Bedroom
      - Sensor__DelayBetweenMeasurementsMs=60000
      - Sensor__I2CBusId=1
      - Sensor__I2CDeviceAddress=40
    devices:
      - /dev/i2c-1:/dev/i2c-1
    networks:
      - homemonitor
