version: "3.6"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
     - "5672:5672"
     - "15672:15672"
     - "15692:15692"
  worker_master_bedroom:
    image: homemonitor/worker
    build:
      context: ./src
      dockerfile: HomeMonitor.worker/Dockerfile
    environment:
      - RabbitMQ__Uri=rabbitmq://rabbitmq:5672
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - AppSettings__Location=Master Bedroom
  worker_family_room:
    image: homemonitor/worker
    build:
      context: ./src
      dockerfile: HomeMonitor.worker/Dockerfile
    environment:
      - RabbitMQ__Uri=rabbitmq://rabbitmq:5672
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - AppSettings__Location=Family Room
  api:
    image: homemonitor/api
    build:
      context: ./src
      dockerfile: HomeMonitor.Api/Dockerfile
    restart: always      
    ports:
     - "5000:80"
     - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Passw0rd
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - RabbitMQ__Uri=rabbitmq://rabbitmq:5672
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
    volumes:
      - ~/.aspnet/https:/https/:ro
