version: "3.6"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    restart: always
    volumes:
      - rabbit-data:/var/lib/rabbitmq/
      - rabbit-log:/var/log/rabbitmq
    networks:
      - homemonitor
  # postgres:
  #   image: postgres
  #   ports:
  #    - "5432:5432"
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: example
  #     PGDATA: /var/lib/postgresql/data/pgdata
  #   volumes:
  #     - postgres:/var/lib/postgresql/data/pgdata
  #   networks:
  #     - homemonitor
volumes:
  postgres:
  rabbit-data:
  rabbit-log:
networks:
  homemonitor:
